### ISSUE TITLE
Input Validatipon

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#1]
Please make sure that all the fields which required validation should be properly validated all across the app and upon pressing the invalid icon it should present the reason for invalidating the field.

- [x] 1. Activation or SIM Replacement or Number Portin / SIM Scan / IMSI should be of format ^4220214[0-9]{8}$
- [x] 2. Mobile number should be validated with ^[79][0-9]{7}$ all across the application
- [x] 3. All contact numbers () should be validated with ^[279][0-9]{7}$ all across the application
- [x] 4. All the mobile numbers and contact numbers and IMSI in the application should allow only digits input and no other character and not even dot (.)
- [x] 5. Recharge > Recharge By Voucher > Enter PIN number --> The message should tell that "**please enter a valid 16 digit recharge pin**".

**Comment by mobiloitte-quality** [comment]
**Mobiloitte comment:** Done

**Comment by pmadiset** [comment]
Under activation / SIM replacement and in Mobile number portability, the MSISDN and IMSI are not validated  Hence kept the points 1 & 2 open.

I have a type in point 4. I have corrected now. We should not allow dot(.) also.

**Comment by mobiloitte-quality** [comment]
Under activation / SIM replacement and in Mobile number portability, the MSISDN and IMSI are not validated Hence kept the points 1 & 2 open.
Point 1: **Mobiloitte comment:** Already added the above regix
Point 2: **Mobiloitte comment:** Already done

Point 4: I have a type in point 4. I have corrected now. We should not allow dot(.) also.
**Mobiloitte comment:** Already done

**Comment by pmadiset** [comment]
1 & 2 Please check below screen shot. The input is not validating and allowing to activate.
![image](https://user-images.githubusercontent.com/30493900/28823932-f142349e-76d0-11e7-898a-ee1dc516c043.png)

4) Please check the screen shots below.  Still allowing other characters. Below are only samples. You need to review complete application.
![image](https://user-images.githubusercontent.com/30493900/28824000-3c9ad388-76d1-11e7-85a6-9ffbcbe33310.png)
![image](https://user-images.githubusercontent.com/30493900/28824031-567e3db2-76d1-11e7-8cbf-8d62cd792255.png)

**Comment by mobiloitte-quality** [comment]
**Mobiloitte Comment:** We are using same regix whatever you have shared here.
if anything is need to be changed, please let us know.

**Comment by pmadiset** [comment]
Dear, This regular expression you have implemented every where how this will not work here on this page.

**Comment by mobiloitte-quality** [comment]
I've cross checked with my team yesterday and I'll do that again for you, and comment you the same.

**Comment by mobiloitte-quality** [comment]
1. Activation or SIM Replacement or Number Portin / SIM Scan / IMSI should be of format ^4220214[0-9]{8}$
**Mobiloitte comment:** Done. Tested and verified. 
2. Mobile number should be validated with ^[79][0-9]{7}$ all across the application
**Mobiloitte comment:** Done.  
4. All the mobile numbers and contact numbers and IMSI in the application should allow only digits input and no other character and not even dot (.)
**Mobiloitte comment:** Done.

**Comment by mjov** [comment]
APP Ver1.8

point 1) & 3) not resolved - still allows text keyboard, and entering any number digit
workflow validation is also wrong - app wrongly "ticks" (green tick) at any input as long as the length of the input is met  - this must be corrected

TeamV session at:
https://www.dropbox.com/s/74d92y4gx1xvtdi/SIMScan_inputValidation.tvs?dl=0
