### ISSUE TITLE
SIM Scan Feature

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#11]
All the below issues are applicable for all Activation | SIMM Replacement | Mobile Number Portability pages
### When the SIM scan is tapped

- [x] 1) Immediately open the barcode scanner
- [x] 2) Send the scanned text to API, which returns the two values for MSISDN and IMSI.
- [x] 3) Populate these values in the MSISDN and IMSI fields under this section
- [x] 4) If any of these fields are empty then only slide down the SIM Scan section to enter the details manually otherwise just tick the SIM Scan section and proceed.

### Other Issues
- [x] The fields MSISDN and IMSI under SIM Scan fields should be editable
- [x] Add barcode scanner button on the right side of both MSISDN and IMSI fields toward sight side of the field.

**Comment by mobiloitte-quality** [comment]
1) Immediately open the barcode scanner 
 2) Send the scanned text to API, which returns the two values for MSISDN and IMSI.
 3) Populate these values in the MSISDN and IMSI fields under this section
 4) If any of these fields are empty then only slide down the SIM Scan section to enter the details manually otherwise just tick the SIM Scan section and proceed.

**Mobiloitte comment:** Already defined that this will be done during the functionality implementation of the UI build.

**Comment by mobiloitte-quality** [comment]
The fields MSISDN and IMSI under SIM Scan fields should be editable
 Add barcode scanner button on the right side of both MSISDN and IMSI fields toward sight side of the field.

**Mobiloitte comment:** Done

**Comment by pmadiset** [comment]
Will close this after functionality implementation.

**Comment by mjov** [comment]
Hi,
please find the comments based on the testing done on version 1.6 related to SIM scan worflow:

1. opening the barcode scanner (item list 1. above) is not implemented on the SIM Change screen and workflow

2. app crashing on SIM change screen when trying to scan MSISDN/IMSI number fields 

3. scanning the MISDN field returns an error as it expects IMSI number on all screens (Activation, MNP, SIM change)

4. editing the MSISDN filed gives full keyboard, we need  a numeric keyboard only for entering MSISDN number + seems that standard logic for mobile number field is not implemented  

5. Marking the workflow finished (green tick-mark) comes soon you enter a single character in any of the missing fields. Requirements are to mark this workflow complete, only after verification with the back-end, hence either on: a) return of both  MSISDN and IMSI from the kit-barcode, or b) when entering/scanning manually, after back-end confirmation that MSISDN and IMSI pair is correct

**Comment by mobiloitte-quality** [comment]
**Mobiloitte comment:** Please check on the following points as we have worked on these points only. 

Please **note** that SIM Change screen is not in the Priority-1 list. 

API implemented as per priority 1:
1. Login api.
2. Manage Otp verification.
3. Activation api.
4. Get SIM info(Activation and Mobile number portability).
5. Pre Activation ID verification.
6. Mobile number portability.
7. Forgot password.
8. Number verification.
9. Registration Api.
10. Reset Password.
11.Change Password.
12.Logout api.
13.Manage Get App Setting for whole app.
14.Terms and condition
15.privacy policy
16.help screen
17.FAQ screen

**Comment by mobiloitte-quality** [comment]
We are working on the SIM Change screen, and we'll update you by EOB today.

**Comment by mobiloitte-quality** [comment]
Dear Milan,

Please find the inline comments based on the testing done on version 1.6 related to SIM scan workflow:

1. opening the barcode scanner (item list 1. above) is not implemented on the SIM Change screen and workflow
**Mobiloitte comment:** Done

2. app crashing on SIM change screen when trying to scan MSISDN/IMSI number fields
**Mobiloitte comment:** Done

3. scanning the MISDN field returns an error as it expects IMSI number on all screens (Activation, MNP, SIM change)
**Mobiloitte comment:** Done

4. editing the MSISDN filed gives full keyboard, we need a numeric keyboard only for entering MSISDN number + seems that standard logic for mobile number field is not implemented
**Mobiloitte comment:** Done

5. Marking the workflow finished (green tick-mark) comes soon you enter a single character in any of the missing fields. Requirements are to mark this workflow complete, only after verification with the back-end, hence either on: a) return of both MSISDN and IMSI from the kit-barcode, or b) when entering/scanning manually, after back-end confirmation that MSISDN and IMSI pair is correct
**Mobiloitte comment:** Done

6. MSISDN is not provided in Customer Information (phone number) section after collecting the SIM Scan info
**Mobiloitte comment:** Done

Please check if all looks fine, please confirm.

**Comment by mjov** [comment]
hi,
Now I can confirm that scanning of MSISDN and IMSI barcodes works fine in a single (first) scan, also including individual scans for each field. 

However, scanning of a new Sim Kit single bar code seems not working (see a sample of a sim kit bar code attached). 

Please confirm that MT has correct understanding, as agreed and communicated during wire frame and workflow confirmation phase, as well as described in this ticket;  

SIM kit single bar code scan will be sent to a backend for verification and backend should return MSISDN and IMSI values. Is this logic implemented?  
![img_20170814_191152771](https://user-images.githubusercontent.com/14956552/29278683-894bf2c0-8126-11e7-8fbe-cd2aea1102d9.jpg)

**Comment by mobiloitte-quality** [comment]
Please look into the response, it is responding to null, and so we have such result. 

**request:**
{"AccessToken":"#7NSJBQNI8D6HM.J*JH.P#TQLWZ8F#R0O*7HMKLSIJ_#ASG85R","DeviceId":"a9a078d17990ef23","SIMCardInfo":{"ScanData":"0DKGLTL"}}

**response:**
{"SIMInfo":{"imsi":"","msisdn":""},"StatusCode":"0","StatusText":"Kit information retrieved successfully"}

**Comment by pmadiset** [comment]
Dear All, sorry for the confusion caused. The Kit code **0DKGLTL** was present in production and not in development. Please check now as we created this data in development now.

**Comment by mjov** [comment]
Hi; the SIM scan seems to be almost functional, however, we need to confirm the following two from the initial list: 

- [ ] 2) Send the scanned text to API, which returns the two values for MSISDN and IMSI.
is this logic implemented for all scan/manual scenarios for both fields? when entry is manual, it seems that only field mobile number verification is applied and there is no back end API verification with API to verify that IMSI/MSISDN pair is valid? @pmadiset, may be you want to clarify this first:
 
- [ ] 4) if any of these fields are empty then only slide down the SIM Scan section to enter the details manually otherwise just tick the SIM Scan section and proceed.
Also, in case we are reading only a single parameter (MSISDN or IMSI), we need to drop down the category and point the user to a missing field for re-scan or manual re-entry

**Comment by mobiloitte-quality** [comment]
@pmadiset we need to discuss on this

**Comment by mjov** [comment]
the issue under point 4) described above  is still present in Ver1.8 - once again, in case of APP scans only one of the numbers MSISDN or IMSI, APP should drop down the category and position the cursor on the missing field

please check the video:
https://www.dropbox.com/s/nee9hsqvchi6xs3/File%20Aug%2023%2C%2019%2030%2009.mov?dl=0

TeamV session:
https://www.dropbox.com/s/fzv9d3z2bochao6/SimScan_recorded_Session.tvs?dl=0

in regards to issue point 2) described above, we are still not verifying the pair between IMSI/MSISDN even at the end of the workflow. @pmadiset , please make sure this is communicated and API provided accordingly

TeamV session for full SIM registration Activation workflow provided here:
https://www.dropbox.com/s/5r36zmno7dy8apm/Activation_workflow.tvs?dl=0
 
regards,
Milan
