### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#13]
Screen should be responsive on portrait/landscapes for tablet screens

- Still not responsive on the test phone we used (see note below)

Main Action icons space (4 circle)  

- still not centered between the scrolling banner and footer menu

4 circle is becoming ellipsoid on 5” screen phones

- it is expected that APP is dynamically responsive to different size of the phone screens and resolutions

**Comment by pmadiset** [comment]
On my screen all home page is showing all nice circles. When I go from landscape to portrait then all the circles become ellipse.

I recommend while in landscape hide the banners such that you can properly fit the circles.

**Comment by mobiloitte-quality** [comment]
These are the new changes and will share the estimate for the same after agreed scope gets approved.

**Comment by mobiloitte-quality** [comment]
Please Comment

**Comment by mjov** [comment]
Hi; we need to understand why is this classified as 'new change'? As already elaborated on Basecamp, our initial specifications are requesting a responsive design for different sizes of the screen.

**Comment by mobiloitte-quality** [comment]
We have agreed to the scope that the screens will be on Portrait Mode only.
![scope](https://user-images.githubusercontent.com/30585486/28817005-b92876ba-765b-11e7-9cac-b974572358ff.PNG)

Still we have added the landscape mode for the "Dashboard Screen" and if you wish for the Home screen, we'll have to change entire application and share the estimate as well as we have take the base of the entire application in Portrait mode only.

**Comment by mjov** [comment]
hi;
I do acknowledge that proposal does state portrait mode only. Can you clarify what "online" means? 

In any case; we do expect that portrait mode should be responsive to various different screen sizes and resolutions and we shall assure that this part is without any big disturbance to graphic design and UX. 

We are expecting that devices used in distribution network on BYOD model, may vary in different screen size and resolution: from  5" - 7" for phones size and commonly used 8" tablet devices.

**Comment by mobiloitte-quality** [comment]
I do acknowledge that proposal does state portrait mode only. Can you clarify what "online" means?
**Mobiloitte Comment:** Online means :  Application will not work without internet connectivity.

In any case; we do expect that portrait mode should be responsive to various different screen sizes and resolutions and we shall assure that this part is without any big disturbance to graphic design and UX.
**Mobiloitte Comment:**  Yes, this is responsive for all android phone devices.

We are expecting that devices used in distribution network on BYOD model, may vary in different screen size and resolution: from 5" - 7" for phones size and commonly used 8" tablet devices.
**Mobiloitte Comment:** For all phone version its compatible but for Tablet, it is not in our scope and hence its not done for tablet.  Same phone version apk can also be installed on android tablet but tablet version is not in my scope and hence we are not checking anything on tablet.

**Comment by mobiloitte-quality** [comment]
Please comment

**Comment by mjov** [comment]
we must include tablet, as our estimates are that 8" screen tablets are commonly used in dealer distribution network. 

i will discuss this part with Rajdeep, our understanding is that this should be covered from initial discussions we had before starting the project

**Comment by mobiloitte-quality** [comment]
We've checked the build in samsung tab- T311 - 8" screen and its seems absolutely fine where only Dashboard  screen is in landscape, rest others in portrait.

**Comment by mjov** [comment]
the main 4 circlies are still stretched and look like ellipsoids rather than circles. How do we resolve this issue?

![5a](https://user-images.githubusercontent.com/14956552/29484035-496b5bd8-84c7-11e7-8137-58d2baf46d10.jpg)

**Comment by mobiloitte-quality** [comment]
Hi Milan,

We are having a week off today, can we discuss on all the points on Monday?

**Comment by mjov** [comment]
sure
