### ISSUE TITLE
AccessKey in all API calls from PP to CMP

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#15]
Hi Srdjan,

I see that AccessKey is not required for Mobile APP. but you (PP) need to add Access Key in all the APIs  and make the request to CMP.

AccessKey is totally private between PP and CP and has nothing to do with Android App

**Comment by mjov** [comment]
@pmadiset 
shall we move this to the other repository for PP integration

**Comment by pmadiset** [comment]
Yes we can.
