### ISSUE TITLE
Dealer Registration - return notification error 

### ISSUE THREAD

**Issue by mjov** [pmadiset/DealerApp#18]
on the fulfillment of all required fields for Dealer account registration, and after submitting <register>,  app returns message:

"unable to decode AuthorizedSignature"

**Comment by mobiloitte-quality** [comment]
>> On the fulfillment of all required fields for Dealer account registration, and after submitting , app returns message:"unable to decode AuthorizedSignature"
**Mobiloitte Comment:** We have checked from our side, in request authorized Signature is sent in current format(base 64). We have also checked through "online base64 to image converter".
