### ISSUE TITLE
Intermediate Regula Scan Preview

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#2]
After successful scan of ID card back side, a temporary regula screen with information is shown with OK button. This screen is not required.

Regula confirmed that this screen can be removed. Please check.

**Comment by mobiloitte-quality** [comment]
We are using regix shared by you for contact number , since  regix contains 0 , so we cannot remove 0.  Please update regix to avoid 0.

**Comment by pmadiset** [comment]
The comment is not appropriate. Please check and post under correct issue.

**Comment by mobiloitte-quality** [comment]
Sorry for this. 

**Mobiloitte comment:** This will be done during functional work.

**Comment by mobiloitte-quality** [comment]
Please Comment

**Comment by pmadiset** [comment]
Ok
