### ISSUE TITLE
APP crashing - CR Number (QR scan)

### ISSUE THREAD

**Issue by mjov** [pmadiset/DealerApp#20]
when selecting scan for CR number under Dealer Registration screen

**Comment by mobiloitte-quality** [comment]
**Mobiloitte Comment:** Done

**Comment by mjov** [comment]
hi;
i would assume we will be seeing this in the next released version, please confirm

**Comment by mobiloitte-quality** [comment]
Yes, We'll resolve all the issues and update u with the latest build.

**Comment by mobiloitte-quality** [comment]
Resolved, Please check and confirm!

@pmadiset  Please verify all the gitHub points and close the bucket, if it seems fine from your end.

**Comment by mjov** [comment]
this is resolved now
