### ISSUE TITLE
error on submitting Dealer registration 

### ISSUE THREAD

**Issue by mjov** [pmadiset/DealerApp#21]
on completing dealer registration form, error on "expired Employee ID card"

same ID card was used on sponsor and employee details  
![image](https://user-images.githubusercontent.com/14956552/29484173-0c5fd7ca-84ca-11e7-81cd-73763ee5cc5b.png)

**Comment by mobiloitte-quality** [comment]
I think we need to check from the back end side that, expired employee id appears in what case of registration api response? We are sending employee id, when that is fetched from regula scanner as a request.

**Comment by pmadiset** [comment]
Server side issue corrected.
