### ISSUE TITLE
ID front side - camera capture (Samsung Prime+) blank screen

### ISSUE THREAD

**Issue by mjov** [pmadiset/DealerApp#22]
Hi;
we are getting a full blank screen at the second "Cropping screen"  camera capture activity with   Samsung Prime+ phone

Attahed are screen shots and  phone details:

![image](https://user-images.githubusercontent.com/14956552/29492320-2f46e98a-8589-11e7-9a89-886adf63e710.png)

**Comment by mjov** [comment]
hi; i think this is not appropriate comment for the subject raised under this issue case

**Comment by mobiloitte-quality** [comment]
We have managed and tested on all the Samsung devices, Vivo, Xperia and Intex, hope you'll not face anything like that.

**Comment by mjov** [comment]
@pmadiset , let's test it with our Samsung test phone and revert in case we observe same in 1.8ver

**Comment by mobiloitte-quality** [comment]
Hi @mjov / @pmadiset , 

We have done on the point footer menu animation and making company fields optional.. Shall I provide new apk? And you begin testing on that?

**Comment by mjov** [comment]
hi; i think we have a different issue #8 - for this particular case... we will provide comments there once tested

**Comment by ShahidSaud** [comment]
We tested on the Samsung Galaxy Grand Prime+ and getting the same issue.. The screen goes blank when we capture the ID card front side image. Not sure is it a Firmware issue , model or software issue.

Usually, in these cases we suggest to have some debug information from the app which records all the trace details that could help to nail in this issue.

**Comment by mobiloitte-quality** [comment]
We have tested in samsung device. Working fine.
