### ISSUE TITLE
ID front side - "cropping screen" (low memory warning)

### ISSUE THREAD

**Issue by mjov** [pmadiset/DealerApp#23]
hi,
on some phones (MotorolaX 2nd gen, Sony Xperia-L1)  - we are noticing a low memory warning. This appears to be a case where app is trying to do "auto-cropping" of the captured picture 

![image](https://user-images.githubusercontent.com/14956552/29492345-e7b5697e-8589-11e7-9d3f-fddac6e93a4a.png)

**Comment by mobiloitte-quality** [comment]
Here we've used library, where it shows by default- low memory dialog, where it checks internally, the device memory, and it shows low memory in the case when actually there is low memory in the device.

**Comment by mjov** [comment]
can be controlled by the library and we ignore the error message?

**Comment by mobiloitte-quality** [comment]
We can ignore the error message, but it cannot be saved in device memory due to low space, so feasibility says to add library with this logic. Please advice.

**Comment by mjov** [comment]
this seems to be resolved now ... i am closing the issue
