### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#25]
- [x] If the Services URL is not reachable the Ajax Loading window covers the Logo. Instead There should not be any over lay on splash screen. You can Keep an Ajax bar indicating that the APP is processing something.

If the Services URL is not reachable, a message pops UP After 3 to 4 minutes saying "Server not responding"

- [x] The time for raising the message or time out should be decreased to "20 Sec"

- [x] After tapping on "OK" on the server not responding, the application does not exit, The APP still hangs on Splash screen

- [x]  Please confirm that the copy right information always takes the current year and the year is not hard coded.

- [x] App Services URL should be taken from the link http://www.rennamobile.com/DealerAppApiLocation.json <- This will be useful in migrating the services to a new server any time.

- [x] Complete network is off. When the APP is opened , it gives a message "Please check your internet connection". After tapping OK, the app still in foreground in splash screen with busy. After tapping OK the APP should close.

- [x] When ever I open the APP, every alternate time, i get the message "Server not responding"

- [x] App shows a complete white screen for a noticeable time before before showing the splash screen.

**Comment by mobiloitte-quality** [comment]
If the Services URL is not reachable the Ajax Loading window covers the Logo. Instead There should not be any over lay on splash screen. You can Keep an Ajax bar indicating that the APP is processing something.
**Comment** : Not doing for now
If the Services URL is not reachable, a message pops UP After 3 to 4 minutes saying "Server not responding" 
**Comment** :  Server is taking its own time, there's no error from our end.
 The time for raising the message or time out should be decreased to "20 Sec"
**Comment** Done
 After tapping on "OK" on the server not responding, the application does not exit, The APP still hangs on Splash screen
**Comment** Done
 Please confirm that the copy right information always takes the current year and the year is not hard coded.
**Comment** Done
 App Services URL should be taken from the link http://www.rennamobile.com/DealerAppApiLocation.json <- This will be useful in migrating the services to a new server any time.
**Comment** Done

**Comment by mobiloitte-quality** [comment]
App shows a complete white screen for a noticeable time before before showing the splash screen.
Comment: As discussed no change required in it.

**Comment by pmadiset** [comment]
Please remove the URL page now and directly take to splash screen.
