### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#26]
- [x] Change the place Holder from "Mobile Number" to "Dealer Mobile Number"

- [x] After 3 consecutive login failures the APP should ask for captcha.

- [x] When entered invalid password, the icon should have a X symbol representing error. And also the size of this icon is very small. The size should be increased.

- [x]  When the captcha is displayed, wrong password is entered wrongly for 3 times. Now entered password wrongly again 4th time. This time captcha is not displayed. Please show captcha for every login attempt after first 3 failures.

- [x] If correct captcha is entered and wrong password, next captcha is showing the same image. If should refresh the captcha image to a new one.

**Comment by mobiloitte-quality** [comment]
Change the place Holder from "Mobile Number" to "Dealer Mobile Number"
**Comment**: Done

 After 3 consecutive login failures the APP should ask for captcha.
**Comment**: Done

 When entered invalid password, the icon should have a X symbol representing error. And also the size of this icon is very small. The size should be increased.
**Comment**: Done

**Comment by pmadiset** [comment]
Added two more comments.

**Comment by mobiloitte-quality** [comment]
If correct captcha is entered and wrong password, next captcha is showing the same image. If should refresh the captcha image to a new one.
Comment: Done
