### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#27]
- [x]  Change the text above the mobile number as "Please provide the registered dealer mobile number. An OTP will be sent to this number"

- [x] The place holder should be "Dealer Mobile Number"

- [x]  OTP Panel says "Please enter 5 digit verification code received on mobile number ending with 98345345". Here "Ending with" is not required as the full number is shown

- [x] When wrong OTP is entered, the user should be provided a chance to enter correct OTP again. Maximum tries should be 3, before the OTP window closes automatically.

**Comment by mobiloitte-quality** [comment]
Change the text above the mobile number as "Please provide the registered dealer mobile number. An OTP will be sent to this number"
**Comment**: Done

 The place holder should be "Dealer Mobile Number"
**Comment**: Done

 OTP Panel says "Please enter 5 digit verification code received on mobile number ending with 98345345". Here "Ending with" is not required as the full number is shown
**Comment**: Done

 When wrong OTP is entered, the user should be provided a chance to enter correct OTP again. Maximum tries should be 3, before the OTP window closes automatically.
**Comment**: Done
