### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#28]
- [x] There should be instructions to user to enter his new password and proceed to reset

- [x] After Successful password reset , the information is presented in a flash message. The message should be shown in a proper window with Green Tick mark to the user that the password rest was successful and proceed to login with new password.

- [x] When the confirm password does not match the new password, upon tapping information icon the flash message is "Password does not match" . This should be changed to "Both new and confirm passwords does not match"

- [x] Upon error, the screen should go back to forget password

**Comment by mobiloitte-quality** [comment]
There should be instructions to user to enter his new password and proceed to reset
**Comment**: Work in progress

 After Successful password reset , the information is presented in a flash message. The message should be shown in a proper window with Green Tick mark to the user that the password rest was successful and proceed to login with new password.
**Comment**: Done

 When the confirm password does not match the new password, upon tapping information icon the flash message is "Password does not match" . This should be changed to "Both new and confirm passwords does not match"
**Comment**: We'll do this, but UI will not look good. Please suggest! 

 Upon error, the screen should go back to forget password
**Comment**: This is not ethical. It should remain in the same screen.

**Comment by mobiloitte-quality** [comment]
There should be instructions to user to enter his new password and proceed to reset
Comment: Done
