### ISSUE TITLE
Registration Screen

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#29]
- [x]  From the Text Above OTP remove "Ending with"

- [x] When QR Is scanned for CR Number field, then it will return a URL something like "https://business.gov.om/wps/PA_OSS3_Portal/external.htm?target=viewCompany&crNumber=1253970", but you need to take only the number after crNumber=

- [x] Unable to Decode any of the images. Please check the attached request that I have received in the server
[2017-09-05-13-31-20.txt](https://github.com/pmadiset/DealerApp/files/1276866/2017-09-05-13-31-20.txt)

- [x] Sending the base 64 header as image/jpg even for PNG images.

- [x] After successful registration the Request is shown is NULL

- [x] The appearance of Success Icon (Green tick mark) is very dull 

- [x] Up on tapping back on the Successful registration the APP still stays on the registration screen. It should be moved to login screen.

- [x] CR Number should be free text. Dont limit to only digits.

- [x] Some times Email field shows as invalid even though entered valid email and enables to submit the form.

- [x] on selecting the category "Company" the positioning of the screen is not correct. it should be positioned at the "Shop name" field

- [x] clicking terms & conditions link takes me to reports page. needs a fix

- [x] i was able to enter very long string of characters under CR number field, let's limit this to max 20. @pmadiset ?

**Comment by mobiloitte-quality** [comment]
We will do this.

**Comment by mjov** [comment]
hi;
i noticed that CR number allows now only numeric entry,  @pmadiset, please clarify if this needs to be corrected, i believe we have CR numbers that include characters as well

**Comment by mobiloitte-quality** [comment]
From the Text Above OTP remove "Ending with"
**Comment**: Done

 When QR Is scanned for CR Number field, then it will return a URL something like "https://business.gov.om/wps/PA_OSS3_Portal/external.htm?target=viewCompany&crNumber=1253970", but you need to take only the number after crNumber=
**Comment**: Done

 Unable to Decode any of the images. Please check the attached request that I have received in the server
2017-09-05-13-31-20.txt
**Comment**: We'll share the screen and test together on this. 

 Sending the base 64 header as image/jpg even for PNG images.
**Comment**: Done

 After successful registration the Request is shown is NULL
**Comment**: Need to be discussed

 The appearance of Success Icon (Green tick mark) is very dull
**Comment**: Done

 Up on tapping back on the Successful registration the APP still stays on the registration screen. It should be moved to login screen.
**Comment**: Same functionality is used. (Working fine)

**Comment by pmadiset** [comment]
After successful registration the Request is shown is NULL
MT Comment: Need to be discussed
Renna: RegisterDealer API response provides RequestId valiable along with status code and status text. This should be displayed for request number.

**Comment by mobiloitte-quality** [comment]
on selecting the category "Company" the positioning of the screen is not correct. it should be positioned at the "Shop name" field>> Done

Some times Email field shows as invalid even though entered valid email and enables to submit the form. >> Not able to reproduce.

After successful registration the Request is shown as > Nota ble to reproduce

**Comment by mjov** [comment]
MQ wrote:
 times Email field shows as invalid even though entered valid email and enables to submit the form. >> Not able to reproduce.

i was able to reproduce and behavior is only when you don't provide email address under the company, and keep only email address under employee
![image](https://user-images.githubusercontent.com/14956552/31215314-0c6fbe0e-a9c0-11e7-9653-e4d150903e86.png)

**Comment by mobiloitte-quality** [comment]
After successful registration the Request is shown is NULL
Comment: Done

clicking terms & conditions link takes me to reports page. needs a fix
Comment: Done

 i was able to enter very long string of characters under CR number field, let's limit this to max 20. @pmadiset ?
Comment: done
