### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#3]
All the animations in the App should not exceed the total time of 0.5 Sec. Please change all across the app.
e.g.  Customer Information

**Comment by mobiloitte-quality** [comment]
**Mobiloitte comment:** Done

**Comment by pmadiset** [comment]
Customer Information taking 2 sec to complete the animation
Dealer Information is taking 1.5 Sec to animate
Employee Information is taking 1.5 Sec to animate
Company information is taking 2.5 Sec to animate

**Comment by mobiloitte-quality** [comment]
**Mobiloitte comment:** Done

**Comment by pmadiset** [comment]
Dear Shikha,
Still not satisfied with the animation. If this can not be done, instead of animating every field separately, animate all the fields together such that we can achieve the target time.

**Comment by mobiloitte-quality** [comment]
**Mobiloitte Comment:** As per the discussion you are asking to animate all text
fields together within total time 0.5 sec. This will be done during functional milestone release.
