### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#31]
- [x]  The banners are associated with links and these links are not working.

**Comment by mobiloitte-quality** [comment]
The banners are associated with links and these links are not working.
**Comment**: There was no such discussion ever made in this in the whole history of rennaM Dealer App! :-P

**Comment by mjov** [comment]
Hi;
I am not sure if we understand the comment? if you refer to a SOW v1.0 shared at very early stage of the project initiation, you will find the following section:
![image](https://user-images.githubusercontent.com/14956552/30276940-78dd9720-9717-11e7-9828-76669c306a49.png)

Basecamp:
https://mobiloitte.basecamphq.com/projects/13822793/file/231888953/RennaM_Dealer_App_Requirements_v1.0.docx  

what would be MT expectation on the links associated with a particular banner?

**Comment by mobiloitte-quality** [comment]
Done, @pmadiset  Please close
