### ISSUE TITLE
Recharge Page

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#32]
- [x] APP Is restarting when the QR code is read. 

- [x] Recharge Online AccessToken is not URL encoded hence we are not able to get the correct AccessToken

- [x] When tapped back from the recharge online page (after clicking recharge) the app is taking the user to Home page where as it should be taking to recharge page.

- [x] After successful transaction the APP is taking to home screen, where as it should remain on same page and fields should be reset.

- [x] Recharge By Voucher --> The PIN number should not allow any text other than numbers. Right now if I scan a QR code with a link, it is accepted as valid input.

**Comment by mobiloitte-quality** [comment]
APP Is restarting when the QR code is read.
**Comment**: Done

 Recharge Online AccessToken is not URL encoded hence we are not able to get the correct AccessToken
**Comment**: Need to be discussed

 When tapped back from the recharge online page (after clicking recharge) the app is taking the user to Home page where as it should be taking to recharge page.
**Comment**: Done

 After successful transaction the APP is taking to home screen, where as it should remain on same page and fields should be reset.
**Comment**: Done
