### ISSUE TITLE
Activation Page

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#33]
- [x]  Images are not getting uploaded as we are not able to decode Base64 image format

- [x] For signature we are getting the image type as JPEG where as it is actually PNG.

- [x] After taking the Signature, auto open the Customer Information

- [x] Please remove the Red Border for Signature

- [x] The resolution of the images is very poor.  Please improve the quality of the images.

- [x] Parameter CustomerIdFrontSide has only header, but no data in version 2.9. Please check.

- [x] The quality of the image is very poor all across the APP. Please fix this.

- [x] Cropping ID card front side is not working. Every where in APP.

- [x] Also the message is conveyed is wrong. Message Box Title should be "Cancel Operation", Box content should be "Are you sure you want to cancel and go back? Form data will be lost"

**Comment by mobiloitte-quality** [comment]
Images are not getting uploaded as we are not able to decode Base64 image format
**Comment**: We have checked from our end, and we'll share our screen to test for the confirmation. 

 For signature we are getting the image type as JPEG where as it is actually PNG.
**Comment**: Done

**Comment by mjov** [comment]
@pmadiset Hi Praveen, was this requested by sales/marketing, or ?
  "After taking the Signature, auto open the Customer Information"

regards,
Milan

**Comment by pmadiset** [comment]
@mjov , No. I have requested this. This gives a chance to the user to review his request before he submits.

**Comment by mobiloitte-quality** [comment]
After taking the Signature, auto open the Customer Information  >> Done
The resolution of the images is very poor. Please improve the quality of the images. >> Done

**Comment by mobiloitte-quality** [comment]
The resolution of the images is very poor. Please improve the quality of the images
Comment: Done

**Comment by pmadiset** [comment]
Added New item
**Parameter CustomerIdFrontSide has only header, but no data in version 2.9. Please check.**

**Comment by pmadiset** [comment]
Added new issue. 
**The quality of the image is very poor all across the APP. Please fix this.**

**Comment by pmadiset** [comment]
- [ ] Cropping ID card front side is not working.

**Comment by pmadiset** [comment]
Images now are coming in full size. This is not acceptable. Image should be of size less than 1000 Pixels to 500 pixels
