### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#35]
- [x]  Smooth scrolling required. Please refer to issue in Notifications

- [x] Transaction time should be right aligned as in notifications.

- [x] The API is providing "Status" this need to be shown in line with date and time, but with left alignment.

**Comment by mobiloitte-quality** [comment]
Smooth scrolling required. Please refer to issue in Notifications
**Comment** : Need to discuss

 Transaction time should be right aligned as in notifications.
**Comment**: Done

 The API is providing "Status" this need to be shown in line with date and time, but with left alignment.
**Comment**: Done

**Comment by mobiloitte-quality** [comment]
@pmadiset  please close
