### ISSUE TITLE
Mobile Number Portability

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#37]
- [x]  Present operator, every time, when open the pull down, the value is reset, instead the value should be retained and the selected option should be highlighted.

- [x] Under customer Information section, both Present Phone Number  and the the Phone number from SIM Data should be displayed. The label for Phone number from SIM Data should be "Temporary Phone Number"  instead if just "Phone Number"

- [x] After taking the Signature, auto open the Customer Information

- [x] Alternate Number not accepting land line numbers (8 digit number starting with 2)

**Comment by mobiloitte-quality** [comment]
Present operator, every time, when open the pull down, the value is reset, instead the value should be retained and the selected option should be highlighted.
**Comment**: We need time for this, and so we need to discuss on this. 

 Under customer Information section, both Present Phone Number and the the Phone number from SIM Data should be displayed. The label for Phone number from SIM Data should be "Temporary Phone Number" instead if just "Phone Number"
**Comment**: we need to discuss on this.
