### ISSUE TITLE
Request Stock

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#39]
- [x] Not happy with UI. completely different with the Application. Please come up with your own UI.

- [x] Validation is not proper. Select the Product, Enter the quantity and submit. Request is submitted to the server and no data is passed. Looks like after filling the informaiton tapping the Green+ icon is mondatory to record the information. 

- [x] After Successful submission of Request the APP shows the success screen, but it does not have any button.

**Comment by mobiloitte-quality** [comment]
Not happy with UI. completely different with the Application. Please come up with your own UI.
**Comment**: https://github.com/pmadiset/DealerApp/issues/9

**Comment by pmadiset** [comment]
@mobiloitte-quality Issue is still open. UI Ok. but not the look and feel.

**Comment by mobiloitte-quality** [comment]
@pmadiset please suggest

**Comment by pmadiset** [comment]
@mobiloitte-quality  Please come up with few designs

**Comment by mobiloitte-quality** [comment]
Not happy with UI. completely different with the Application. Please come up with your own UI.  Done
