### ISSUE TITLE
Wallet History

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#42]
- [x]  Font is too big. Please make it consistent with Transaction History

- [x] API is now providing status and bonus fields in response. Please accommodate them in the display as per the attached image.

- [x] Please present time in words as well (e.g. now, 1 sec, 2 mins, 4 hours, yesterday, 2 days etc)

![image](https://user-images.githubusercontent.com/30493900/30918300-33845232-a3af-11e7-8a0b-7a664a6e9ec9.png)

**Comment by mobiloitte-quality** [comment]
Font is too big. Please make it consistent with Transaction History
Commnet: Done

API is now providing status and bonus fields in response. Please accommodate them in the display as per the attached image.
Comment: Done, if we get zero from API than it will not show value more than 1 will show.

Please present time in words as well (e.g. now, 1 sec, 2 mins, 4 hours, yesterday, 2 days etc)
Comment: Please provide time in api.

**Comment by pmadiset** [comment]
I have implemented what ever required form server side only. Need one thing form APP.
Currently the APP is showing The color red if('status'=='Failure') can you change the condition id('status_code'!='OK')

**Comment by mobiloitte-quality** [comment]
API is now providing status and bonus fields in response. Please accommodate them in the display as per the attached image.
Comment: Done

 Please present time in words as well (e.g. now, 1 sec, 2 mins, 4 hours, yesterday, 2 days etc)
Comment: Pending from API if we have mange from front end it is require extra effort because 
Comment: Done

**Comment by mobiloitte-quality** [comment]
API is now providing status and bonus fields in response. Please accommodate them in the display as per the attached image.
Cooment: Done
