### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#43]
- [x] Clicking on Reports is giving blank Page.

- [x] Reports view should present the From Date and End Date, default to beginning of the month and current day of the month and clicking on Go button should generate the report. This was already present in previous versions and seem that it is missing in last few versions.

- [x] When Reports is clicked, the request is being received by Server and server is responding with complete HTML content, where as the request should be submitted only after clicking on the Go button.

**Comment by mobiloitte-quality** [comment]
Clicking on Reports is giving blank Page.

 Reports view should present the From Date and End Date, default to beginning of the month and current day of the month and clicking on Go button should generate the report. This was already present in previous versions and seem that it is missing in last few versions.

 When Reports is clicked, the request is being received by Server and server is responding with complete HTML content, where as the request should be submitted only after clicking on the Go button.

Comment:  (In report you have change API so we are not getting data in report screen thats why its showing blank page) If you want change we can share effort for this point.

**Comment by pmadiset** [comment]
Dont send OnlyHtml such that the API returns JSON.

**Comment by mobiloitte-quality** [comment]
Reports view should present the From Date and End Date, default to beginning of the month and current day of the month and clicking on Go button should generate the report. This was already present in previous versions and seem that it is missing in last few versions.
Comment Done

 When Reports is clicked, the request is being received by Server and server is responding with complete HTML content, where as the request should be submitted only after clicking on the Go button.
Comment: Done

**Comment by mobiloitte-quality** [comment]
Reports view should present the From Date and End Date, default to beginning of the month and current day of the month and clicking on Go button should generate the report. This was already present in previous versions and seem that it is missing in last few versions.
Comment: Done
