### ISSUE TITLE
E-Wallet

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#44]
- [x] Monely field should allow only numeric keyboard, right now the keyboard shows alphanumeric keyboard.

- [x] After selecting an amount and clicking on Add is going to page represented by RechargeOnlineURL, where as it should go the page represented by TopUpEWalletURL

- [x] Rename the heading "Add Money(OMR)" to "Add Money to E-Wallet"

- [x] All the denominations are not visible (e..g 2000). May be reducing the margin and sharp edges can give more space.

**Comment by mobiloitte-quality** [comment]
Monely field should allow only numeric keyboard, right now the keyboard shows alphanumeric keyboard.
Comment: Done

After selecting an amount and clicking on Add is going to page represented by RechargeOnlineURL, where as it should go the page represented by TopUpEWalletURL
Comment: This is change we can share effort if you want to implement.

 Rename the heading "Add Money(OMR)" to "Add Money to E-Wallet"
Comment: Done

 All the denominations are not visible (e..g 2000). May be reducing the margin and sharp edges can give more space.
Comment: Its depend upon size of device.

**Comment by mobiloitte-quality** [comment]
After selecting an amount and clicking on Add is going to page represented by RechargeOnlineURL, where as it should go the page represented by TopUpEWalletURL
Comment: Done
