### ISSUE TITLE
UAT Issues

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#57]
- [x] 01) App Takes a long time to start/open

- [x] 02) When we open the app every alternate time we get to see the message "Server not responding"

- [x] 03) App Dashboard is crashing when there is a balance.

- [x] 04) Terms and Conditions in Actvation & SIM  Change & in Mobile Number Portability T &C in signature screen should show from setting "Pages.ActivationT&C" and not from "Pages.DealerAppT&C", this was working fine earlier, but in recent versions this is changed.

- [x] 05) Layout of the app is not proper in phone that are set with Arabic as their phone language. Please check the attached screenshot.

- [x] 06) My Details and Agent Details should show Employee.contact_name. Looks like the APP is now showing Company.contact_name

- [x] 07) While getting the Agent details, in case of any error, the screen is still on Agent details screen. The display should go back to Agents list.

- [x] 08) When clicked on Delete button in Agent Details, a confirmation should be taken before calling the API. 

- [x] 09) APP is not responding some times and keeps showing only the splash screen.

- [x] 10) On Recharge Page, rename "Recharge from Dealer Balance" to "Recharge from Wallet"

- [x] 11) On Recharge Page, for "Recharge from Dealer Balance" and "Dealer Balance Transfer" before submitting the form, please take a confirmation.

- [x] 12) Setting: T&C should point to Pages.DealerAppT&C

- [x] 13) When pressed on any link in T&C, no action is taken. (a blank screen is shown), instead the URL page should be loaded in a browser.

- [x] 14) On Create Agent/ Register/ Edit Agent / Edit My details, under employee section place holder for signature should be "Employee Signature".

- [x] 15) Contact US > Call Center Rename "Call now" to "Call for FREE"

- [x]  16) After activation response is displayed. up on pressing X button, the window is not closing.

- [x]  17) When the Phone language is set to Arabic, all the Date values sent through MRZ scanner are coming in Arabic. Please check the attached Request Dump. [ActivateMobileNumber_2017-10-16-10-56-03.txt](https://github.com/pmadiset/DealerApp/files/1390032/ActivateMobileNumber_2017-10-16-10-56-03.txt)

- [x] 18) E-Wallet Page, when the balance is 0, then the balance is not shown in this Page.

- [x]  19) E-Wallet Page, Balance should always be shown with units. e.g. RO 1.5  RO 0. etc.

- [x]  20) Delete Agent API provides OTP and APP should take the user to OTP confirmation

- [x] 21) Splash Screen, seems to have some animation, where the logo slides a bit. Please remove this animation.

**Comment by mjov** [comment]
The sample of a screen on the phone that has Arabic as default language settings ... 

![image](https://user-images.githubusercontent.com/14956552/31606893-6c2dc408-b27b-11e7-96e6-094b4f5d6d0a.png)

**Comment by pmadiset** [comment]
@mobiloitte-quality , please update the status on these pending issues.

**Comment by pmadiset** [comment]
**04) Terms and Conditions in Actvation & SIM Change & in Mobile Number Portability T &C in signature screen should show from setting "Pages.ActivationT&C" and not from "Pages.DealerAppT&C", this was working fine earlier, but in recent versions this is changed.**
Please mind that, in the application there are 2 types terms and conditions. Looks like you have a single page for this and initializing the same.  The T&C in pages Activation/ SIM Replaccement / Number Portability should show Pages.ActivationT&C and rest all should show Pages.DealerAppT&C. 
So the solution is 

- In the current version change every thing to Pages.DealerAppT&C. 

- Create a new Page for Activation T&C and initialize it with Pages.ActivationT&C and link this to the T&C in Activation/ SIM replacement and Mobile number portability.
