### ISSUE TITLE
Contact Us > Geo Location

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#6]
The pin should point to location 23.595538, 58.410418. Right now it is pointing some where else.

**Comment by mobiloitte-quality** [comment]
**Mobiloitte comment:** Done

**Comment by pmadiset** [comment]
In the Excel Feedback sent earlier, I have also mentioned to change the address under the map to below.
**Street No. 246, Block No. 238, 2nd Floor
Ghubra Plaza, 18th November street,
Al Ghubra, Muscat**
I have missed to follow up on this and so the team. Please change the address too.

**Comment by mobiloitte-quality** [comment]
**Mobiloitte comment:** Done
