### ISSUE TITLE
Change Password and Reset Password

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#7]
- [ ] 1. Currently Change Password screen is checking for various conditions. Only check should be of 5 characters minimum.
- [ ] 2. The validation is being done after tapping Submit. Please do inline validation not after submit.
- [x] 3. Change the hint from "Confirm Password" to "Confirm New Password"

**Comment by mobiloitte-quality** [comment]
**Mobiloitte comment:** Done

**Comment by pmadiset** [comment]
Point 1) clearly says that 5 characters minimum. But what is implemented is 5 DIGITS.  Please make the New Password field to take any characters minimum 5 length.
Point 2) New Password and Confirm New Passwords matching is shown after hitting Submit. Can you show in line.

**Comment by mobiloitte-quality** [comment]
**Mobiloitte comment:** Done
