### ISSUE TITLE
Requests Page

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#9]
1. Change the title to "Request Stock"
2. Please check below the sample layout and implement the same.
![image](https://user-images.githubusercontent.com/30493900/28753549-9a295b5a-7546-11e7-86e0-cada9ff1587f.png)

**Comment by mjov** [comment]
Hi @pmadiset , i see no sample. Pls try to re-upload

**Comment by pmadiset** [comment]
From Mobiloitte Comment: This screen already change twice , so we will share effort after your approval on agreed scope of work

**Comment by pmadiset** [comment]
We have been asking the team to implement the depicted one, but some how team was not able to understand doing changes in other ways.

**Comment by mjov** [comment]
please refer to message on Basecamp from 30th of May, where we provided a sample of the screen we suggest for implementation. Since then, we are not able to get his screen right ...

https://mobiloitte.basecamphq.com/projects/13822793-rennam-dealer-android-app-17042915/posts/102380717/comments#comment_366703033

**Comment by mobiloitte-quality** [comment]
Dear Milan,

We're adding the above screens and will provide you the build after functionality implementation. 

Thanks,
Shikha

**Comment by mjov** [comment]
- [ ] it takes a long time after "select a product" until drop-down of products is displayed, while no indications that app is 'busy' or loading the list

- [ ] flash-message information is displaying that product is already selected after adding new item

- [ ] the qty is not acceptable until typed even tho it displays the QTY from previously confirmed item

![screenshot_20170819-101914](https://user-images.githubusercontent.com/14956552/29484091-83569c9e-84c8-11e7-8342-e0f291d14287.png)
![screenshot_20170819-101927](https://user-images.githubusercontent.com/14956552/29484093-8d41c742-84c8-11e7-9919-b6b8571f0b11.png)

**Comment by mobiloitte-quality** [comment]
Right, we are updating the screen and managing things.

**Comment by mjov** [comment]
thanks! workflow and UI is ok now
can you confirm before we close the case if submission (OK) is implemented, or this is part of M4?
